[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pymonzo"
authors = [{name = "Paweł Adamczak", email = "pawel.ad@gmail.com"}]
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
keywords = ["monzo", "api"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
dynamic = ["version", "description"]

dependencies = [
  "Authlib",
  "httpx",
  "pydantic",
  "structlog",
]

[project.optional-dependencies]
tests = [
  "pytest",
  "pytest-mock",
  "pytest-recording",
]
docs = [
  "mkdocs",
  "mkdocs-gen-files",
  "mkdocs-include-markdown-plugin",
  "mkdocs-literate-nav",
  "mkdocs-material",
  "mkdocs-section-index",
  "mkdocstrings[python]",
]
dev = [
  "pymonzo[tests,docs]",
  # Checks
  "bandit",
  "interrogate",
  # Code style
  "black",
  "isort",
  # Linters
  "dlint",
  "flake8",
  "flake8-bugbear",
  "flake8-comprehensions",
  "flake8-docstrings",
  "flake8-print",
  "flake8-pytest-style",
  "flake8-simplify",
  "pep8-naming",
  # Type checking
  "mypy",
  # Other
  "flit",
  "tox",
]

[project.urls]
Home = "https://github.com/pawelad/pymonzo"

[tool.bandit]
skips = ["B101"]

[tool.black]
target-version = ["py37"]

[tool.interrogate]
ignore-init-module = true
ignore-nested-classes = true

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.7"

[[tool.mypy.overrides]]
module = [
  "authlib.integrations.httpx_client",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --verbose"
testpaths = "tests"
